# Generated by Django 4.1.6 on 2023-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('birthplace', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
